### ISSUE TITLE
About contract 0x9b869c2eaae08136c43d824ea75a2f376f1aa983 DAI-HRD (DAI-HRD)

### ISSUE THREAD

**Issue by mrsolgsm** [Keydonix/dai-hrd#39]
Good day. 

Sorry for writing here, I could not find other contacts.

How can I contact the owner of the address 0x2938a347d93145d49289e0dad06489121a8b6daa from which the contract 0x9b869c2eaae08136c43d824ea75a2f376f1aa983 DAI-HRD (DAI-HRD) was created? 
I have a very good and interesting business proposal for him. This is not a redemption of the address, not an investment, not a prepayment, etc. 
Contact me please at email mr.xtraf@gmail.com

**Comment by MicahZoltu** [comment]
If you have feedback/suggestions/questions about DAI-HRD you can ask in this repository.  This is a trustless contract, so the deployer doesn't matter.  My guess is it was just a one-time use address or something and has since been lost/discarded/thrown away.

**Comment by mrsolgsm** [comment]
It's a pity that he was lost. The question is for 10 thousand us.
